# Generated by Django 3.2.7 on 2021-09-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
    ]
