# Generated by Django 3.2.7 on 2021-09-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
    ]
